x-env_tty: &env_tty
  env_file:
    - .env
  tty: true
  stdin_open: true
x-bind_mount: &bind_mount
  volumes:
    - type: bind
      source: .
      target: /root/app
  working_dir: /root/app
  platform: linux/amd64
services:
  app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Etc/UTC}
    !!merge <<: [*bind_mount, *env_tty]
    entrypoint: zsh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
