name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## IMPORTANT
        For critical security vulnerabilities, please follow our responsible disclosure process by emailing security@example.com instead of filing a public issue.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe do you consider this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
        - Informational
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the vulnerability
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Perform action '....'
        4. Observe security issue
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this vulnerability if exploited?
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for how to fix or mitigate this vulnerability, please provide them here
  - type: input
    id: affected_versions
    attributes:
      label: Affected Versions
      description: Which versions of the software are affected?
      placeholder: e.g., v1.0.0 - v1.2.3
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure
      description: By submitting this report, you agree to follow our responsible disclosure policy
      options:
        - label: I agree to follow this project's responsible disclosure policy
          required: true
